# Test Configuration for Outfit Generation System
# This file controls how tests are run safely

# Test Environment Settings
environment:
  test_mode: true
  use_mock_services: true
  log_level: DEBUG
  output_directory: "test_output"
  
# Database Settings
database:
  test_database_name: "test_closetgpt"
  use_test_connection: true
  backup_before_tests: true
  cleanup_after_tests: true
  
# API Settings
api:
  mock_openai: true
  mock_firebase: true
  timeout_seconds: 30
  retry_attempts: 3
  
# Test Data Settings
test_data:
  create_mock_wardrobe: true
  create_mock_profiles: true
  sample_size: 10
  
# Service Settings
services:
  outfit_service:
    mock_mode: true
    response_delay_ms: 100
    
  analytics_service:
    mock_mode: true
    log_to_file: true
    
  weather_service:
    mock_mode: true
    default_weather: "sunny"
    
# Test Categories to Run
test_categories:
  outfit_generation: true
  filtering_personalization: true
  data_quality: true
  user_profile_matching: true
  system_integrity: true
  edge_cases: true
  production_readiness: true
  
# Safety Settings
safety:
  require_confirmation: true
  max_execution_time_minutes: 10
  backup_existing_data: true
  stop_on_first_failure: false
  
# Output Settings
output:
  save_detailed_logs: true
  generate_html_report: true
  save_test_data: true
  email_results: false 