name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov flake8 black isort bandit safety
          
      - name: Lint Python code
        run: |
          flake8 src/ --max-line-length=88 --extend-ignore=E203,W503
          black --check src/
          isort --check-only src/
          
      - name: Check Python dependencies for vulnerabilities
        run: |
          safety check --json --output safety-report.json || true
          
      - name: Run security scan
        run: |
          bandit -r src/ -f json -o bandit-report.json || true
          
      - name: Run unit tests
        run: |
          pytest tests/ -v --cov=src --cov-report=xml --cov-report=html
          
      - name: Run validation tests
        run: |
          python run_validation_tests.py
          
      - name: Run comprehensive test suite
        run: |
          python comprehensive_testing_framework.py
          
      - name: Run outfit generation tests
        run: |
          python test_outfit_generation.py
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: |
            backend/coverage.xml
            backend/coverage.html
            backend/comprehensive_test_results.json
            backend/safety-report.json
            backend/bandit-report.json
            
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage 