name: Frontend Tests

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint JS/TS code
        run: npm run lint
        
      - name: Audit Node.js dependencies
        run: npm audit --audit-level=moderate
        
      - name: Run unit tests
        run: npm test
        
      - name: Run type checking
        run: npm run type-check || npx tsc --noEmit
        
      - name: Build application
        run: npm run build
        
      - name: Run Cypress tests
        run: npx cypress run --record false
        
      - name: Upload Cypress videos and screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/videos
            frontend/cypress/screenshots
            
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: frontend-test-results
          path: |
            frontend/coverage
            frontend/.next 